webtalk_init -webtalk_dir D:/project/vivado_work/TDC/TDC/TDC.sim/sim_1/impl/timing/xsim/xsim.dir/tb_tdc_top_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 14 15:20:28 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "685e3aee-e1d6-4b4b-be0b-51f4a70c1229" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b3782a6035c1493eb160f967c903a8cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "225" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 9 185H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3072 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "31200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "221.40_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "84460_KB" -context "xsim\\usage"
webtalk_transmit -clientid 744405713 -regid "" -xml D:/project/vivado_work/TDC/TDC/TDC.sim/sim_1/impl/timing/xsim/xsim.dir/tb_tdc_top_time_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/project/vivado_work/TDC/TDC/TDC.sim/sim_1/impl/timing/xsim/xsim.dir/tb_tdc_top_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/project/vivado_work/TDC/TDC/TDC.sim/sim_1/impl/timing/xsim/xsim.dir/tb_tdc_top_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
